name: Gerar APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Instalar Android SDK
        run: |
          yes | sdkmanager --licenses || true
          sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0"

      - name: Instalar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.13'

      - name: Descompactar projeto
        run: |
          unzip -q ProcuraServico_Facil_Celular.zip

      - name: Compilar APK
        run: |
          cd ProcuraServico_Facil_Celular
          gradle assembleDebug --no-daemon

      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: Procura-Servico-APK
          path: ProcuraServico_Facil_Celular/app/build/outputs/apk/debug/*.apk
